name: immich iOS IPA dev Build
on:
  workflow_dispatch:
jobs:
  buildIPA:
    runs-on: macos-14
    name: build IPA
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          cache: 'false'

      - name: 'Create env file'
        run: |
          sudo xcode-select -s "/Applications/Xcode_15.4.app"
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "APPSTORE=true" >> .env
          echo "${{ secrets.SENTRY_PROPERTIES }}" > ./ios/sentry.properties
          git submodule update --init --recursive

      - name: alias yarn.cmd to yarn
        run: alias yarn.cmd="yarn"

      - name: Install dependencies
        run: yarn install; yarn postinstall

      - name: Pod Install
        run: cd ios && rm Podfile.lock && pod install --repo-update

      - name: build
        run: cd ios && xcodebuild -scheme APM -workspace example.xcworkspace -configuration Release clean archive -archivePath "build/APM.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: archive to ipa
        run: |
          cd ios
          mkdir build/Payload
          mv build/APM.xcarchive/Products/Applications/AzusaPlayer.app build/Payload/AzusaPlayer.app
          cd build
          zip -r immich-test.ipa Payload/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immich-test.ipa
          path: ios/build/immich-test.ipa


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_BRANCH }}-build-${{ steps.date.outputs.date }}
          files: ios/build/immich-test.ipa
          prerelease: true
          target_commitish: ${{ env.GIT_BRANCH }}
